export const weddingConfig = {
  groom: {
    fullName: 'محمد عادل صبيح',
    nickname: 'أبو حسان',
    fatherName: 'السيد عادل خميس صبيح',
  },
  bride: {
    fullName: 'سهام عماد التري',
    fatherName: 'السيد عماد حمدي التري',
  },
  event: {
    date: '26 سبتمبر 2026',
    day: 'السبت',
    dateShort: '26/9/2026',
    time: '6:00 مساءً',
    venue: 'صالة قصر لافندرا',
    venueDetail: 'الصحابة - بداخل نادي الدرج',
    city: '—',
    countdownISO: '2026-09-26T18:00:00',
  },
  media: {
    invitation: '/assets/images/hero/invitation.png',
    heroBackground: '/assets/images/couple/groom.png',
    groomGallery: [
      '/assets/images/groom/groom-1.png',
      '/assets/images/groom/groom-2.png',
      '/assets/images/groom/groom-3.png',
      '/assets/images/groom/groom-4.png',
      '/assets/images/groom/groom-5.png',
      '/assets/images/groom/groom-6.png',
      '/assets/images/groom/groom-7.png',
      '/assets/images/groom/groom-8.png',
      '/assets/images/groom/groom-9.png',
    ],
    bridePhoto: null as string | null,
    engagementVideo: '/assets/videos/engagement-video.mp4',
    engagementVideoPoster: '/assets/images/couple/groom.png',
    engagementSectionBackground: '/assets/images/decor/mahr-background.png',
    backgroundMusic: '/assets/audio/wedding-song.mp3',
  },
  map: {
    lat: 31.515,
    lng: 34.463805,
    mapsUrl: 'https://maps.app.goo.gl/Xjgb2KJNkNRyMtHp9',
    defaultStartLat: 31.515,
    defaultStartLng: 34.450894,
    orsApiKey: import.meta.env.VITE_ORS_API_KEY ?? '',
  },
  naqoot: {
    enabled: true,
    minAmount: 1,
    maxAmount: 500,
    copy: {
      pageTitle: 'نقوط العريس أبو حسان الغالي',
      pageIntro:
        'مو جمع فلوس… هاي فرحة ومحبة تصلّ للعريس وتنوّر ليلته 🕯️',
      pageNote: 'كل شمعة = لمسة حب… والأكثر شموعاً يصير حبيب العريس',
      nameLabel: 'الاسم الي حيظهر للعريس',
      namePlaceholder: 'اكتب اسمك أو لقبك',
      amountLabel: 'كم شمعة حابب تفرّح العريس؟',
      amountHint: 'كل شمعة = 1 شيكل — بقد ما تحب',
      amountPlaceholder: '3',
      messageLabel: 'رسالة محبة بينك وبين العريس رح توصلو عالواتس اب',
      messagePlaceholder: 'مبروك يا أبو حسان… الله يباركلك ويّاك!',
      submit: 'أرسل',
      submitLoading: 'جاري الإرسال…',
      success: 'وصلت شمعتك للعريس! الله يبارك فيك ويفرّح قلبك',
      errorGeneric: 'ما قدرنا نرسلها الآن… جرّب مرة ثانية.',
      errorSupabase: 'لوحة النقوط لسا ما اتفعّلت — العريس بجهّزها قريباً',
      errorName: 'اكتب اسمك حتى يعرفك العريس.',
      errorAmount: 'اختار شمعة واحدة على الأقل.',
      leaderboardTitle: 'من فرّح العريس أكثر؟',
      leaderboardEmpty: 'لا أحد أرسل شموع بعد — كن أول واحد يفرّح العريس!',
      championBadge: 'حبيب العريس',
      programmerButton: 'نسيب العريس',
      programmerTitle: 'رسالة من المبرمج',
      programmerName: 'المهندس محمد التري — نسيب العريس',
      programmerMessage:
        'مرحباً! أنا محمد التري، نسيب العريس والمبرمج 😄\n\nالعريس كان معترض على فكرة النقوط… بس أنا غصب خليتها!\n\nوالله مو جمع فلوس — هي طريقة لطيفة تفرّح أخوك وتخلّيه يحس بمحبتكم. كل شمعة = رسالة حب توصله على الواتس.\n\nانقطّوا العريس بمودة… والعريس بيحبكم!',
    },
  },
  copy: {
    heroEyebrow: 'دعوة لحضور حفل الزفاف',
    heroQuote: 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا',
    heroCta: 'ننتظركم بكل حب',
    splashBismillah: 'بسم الله الرحمن الرحيم',
    splashSubtitle: 'دعوة زفاف',
    splashGroomName: 'محمد',
    splashGroomNickname: 'أبو حسان',
    splashBrideName: 'سهام',
    formalIntro: 'يتشرف آل صبيح و آل التري بدعوتكم لمشاركتنا فرحتنا لحفل زفاف..',
    formalOutro: 'يتم الفرح بقدومكم.. ودامت بيوتكم عامرة بالأفراح',
    footerQuote: 'بوجودكم يتم لنا الفرح والسرور.. والعاقبة لديكم بالمسرات',
    noPhotosNote: 'يمنع التصوير بالجوال',
  },
} as const;

export type WeddingConfig = typeof weddingConfig;
