export const weddingConfig = {
  groom: {
    fullName: 'محمد عادل صبيح',
    nickname: 'أبو حسان',
    fatherName: 'السيد عادل خميس صبيح',
  },
  bride: {
    fullName: 'سهام عماد التري',
    fatherName: 'السيد عماد حمدي التري',
  },
  event: {
    date: '26 سبتمبر 2026',
    day: 'السبت',
    dateShort: '26/9/2026',
    time: '6:00 مساءً',
    venue: 'صالة قصر لافندرا',
    venueDetail: 'الصحابة - بداخل نادي الدرج',
    venueDirectionNote: 'التوجه مباشرة الى الصالة',
    city: '—',
    countdownISO: '2026-09-26T18:00:00',
  },
  media: {
    invitation: '/assets/images/hero/invitation.png',
    heroBackground: '/assets/images/couple/groom.png',
    groomGallery: [
      '/assets/images/groom/groom-1.png',
      '/assets/images/groom/groom-2.png',
      '/assets/images/groom/groom-3.png',
      '/assets/images/groom/groom-4.png',
      '/assets/images/groom/groom-5.png',
      '/assets/images/groom/groom-6.png',
      '/assets/images/groom/groom-7.png',
      '/assets/images/groom/groom-8.png',
      '/assets/images/groom/groom-9.png',
    ],
    bridePhoto: null as string | null,
    engagementVideo: '/assets/videos/engagement-video.mp4',
    engagementVideoPoster: '/assets/images/couple/groom.png',
    engagementSectionBackground: '/assets/images/decor/mahr-background.png',
    backgroundMusic: '/assets/audio/wedding-song.mp3',
  },
  map: {
    lat: 31.515,
    lng: 34.463805,
    mapsUrl: 'https://maps.app.goo.gl/Xjgb2KJNkNRyMtHp9',
    defaultStartLat: 31.515,
    defaultStartLng: 34.450894,
    orsApiKey: import.meta.env.VITE_ORS_API_KEY ?? '',
  },
  naqoot: {
    enabled: true,
    groomWhatsApp: '+972595273790',
    minAmount: 0,
    maxAmount: 500,
    copy: {
      pageTitle: 'نقوط العريس أبو حسان الغالي',
      pageNote: 'الكلمة الحلوة احلى نقوط',
      nameLabel: 'الاسم اللي بيظهر للعريس',
      namePlaceholder: 'اكتب اسمك أو لقبك',
      amountLabel: 'كم شمعة حابب تفرّح العريس؟',
      amountPlaceholder: '0',
      messageLabel: 'رسالة محبة للعريس',
      messageSubLabel: 'رح توصله منسقة على الواتساب',
      messagePlaceholder: 'الف مبارك ابو حسان...',
      whatsappDefaultMessage: 'الف مبارك ابو حسان...',
      submit: 'أرسل',
      submitLoading: 'جاري التحضير…',
      success: 'تم فتح الواتساب — أكّد الإرسال للعريس!',
      errorGeneric: 'ما قدرنا نرسلها الآن… جرّب مرة ثانية.',
      errorSupabase: 'لوحة النقوط لسا ما اتفعّلت — العريس بجهّزها قريباً',
      errorName: 'اكتب اسمك حتى يعرفك العريس.',
      errorAmount: 'عدد الشموع ما بصير سالب.',
      leaderboardTitle: 'من فرّح العريس أكثر؟',
      leaderboardEmpty: 'لا أحد أرسل شموع بعد — كن أول واحد يفرّح العريس!',
      championBadge: 'حبيب العريس',
      programmerButton: 'نسيب العريس',
      programmerTitle: 'رسالة من المبرمج',
      programmerName: 'المهندس محمد التري — نسيب العريس',
      programmerMessage:
        'العريس كان معترض على فكرة النقوط… بس أنا غصب خليتها!\n\nما في احلى من نقوط الكلمة الحلوة والمباركة الطيبة 😍',
    },
  },
  copy: {
    heroInviteLead: 'دعوة لحضور حفل زفاف',
    heroInviteName: 'الاستاذ محمد عادل صبيح',
    heroInviteNickname: 'ابو حسان',
    heroQuote: 'وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا',
    heroCta: 'ننتظركم بكل حب',
    splashBismillah: 'بسم الله الرحمن الرحيم',
    splashSubtitle: 'دعوة زفاف',
    splashGroomName: 'أ. محمد عادل صبيح',
    splashGroomNickname: 'ابو حسان',
    formalIntro: 'يتشرف آل صبيح و آل التري بدعوتكم لمشاركتنا فرحتنا لحفل زفاف..',
    formalOutro: 'يتم الفرح بقدومكم.. ودامت بيوتكم عامرة بالأفراح',
    footerQuote: 'بوجودكم يتم لنا الفرح والسرور.. والعاقبة لديكم بالمسرات',
    noPhotosNote: 'يمنع التصوير بالجوال',
    engagementSubtitle: 'شكرا لكل من ترك بصمة واثر جميل',
    footerMadeBy: 'صنع بحب Eng. Mohammed E Alterri',
  },
} as const;

export type WeddingConfig = typeof weddingConfig;
